package:
  name: cluster-over-sampling
  version: "0.1.2"

source:
  url: "https://files.pythonhosted.org/packages/4b/db/67eadb06d605dfd8ada38e49af6e327945d01492897a0c821e0ac7fdd9f9/cluster-over-sampling-0.1.2.tar.gz"
  sha256: "5a2e19b97e6fdcb29674fbdd9e79803021e39bd93051d4d6d95743925401d115"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.4.3, <=0.5.0
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21, <=0.21.3
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.4.3, <=0.5.0
    - numpy >=1.1
    - python
    - scikit-learn >=0.21, <=0.21.3
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
