package:
  name: cluster-over-sampling
  version: "0.1.1"

source:
  url: "https://files.pythonhosted.org/packages/d6/ff/5359a80c153c66126c6054c498d36068c553776d0a2d8084ceb1cc77cab0/cluster-over-sampling-0.1.1.tar.gz"
  sha256: "03832a637ed52abe933925a0f0fb070126ee1085b6c5cf90d9a227392448efae"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.4.3
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.4.3
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
