package:
  name: cluster-over-sampling
  version: "0.1.0"

source:
  url: "https://files.pythonhosted.org/packages/eb/0a/75be7a7aad1e0832ec140189dd2be188ec5bb0dcc9f8613ae96a87474a7a/cluster-over-sampling-0.1.0.tar.gz"
  sha256: "1f2e273c8eec1562ddaa9d8902ff0959292fb1f8edb4c480b83db569fe58db80"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.4.3
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.4.3
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
