package:
  name: cluster-over-sampling
  version: "0.2.4"

source:
  url: "https://files.pythonhosted.org/packages/bc/13/4050b6187e461ae1b8fe71bcab7524febf17fbef6823e203ac6aa073820b/cluster-over-sampling-0.2.4.tar.gz"
  sha256: "9955e576898aac7ea7a46f4fa48742d0dc962cb0ac4e86e1720178beea38fe4e"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
