package:
  name: cluster-over-sampling
  version: "0.2.3"

source:
  url: "https://files.pythonhosted.org/packages/62/68/6b6f8f7254408f527dc14f6ef28821ba49420a56f807736e4d8f5b8275ec/cluster-over-sampling-0.2.3.tar.gz"
  sha256: "f529654b23989e2539ce6b9fa877dc4dacb028a1fbbb0541855e52fefc3cc975"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
