package:
  name: cluster-over-sampling
  version: "0.2.0"

source:
  url: "https://files.pythonhosted.org/packages/e5/7b/2c01da76f59c89571ea57504e656e120d902154d389a8daea104211009e1/cluster-over-sampling-0.2.0.tar.gz"
  sha256: "01b045a6ac210d9b1e16b70ab5aa7b7860bdee15e3b2e3c78b4653583bb947ff"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >0.6.0
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.0
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
