package:
  name: cluster-over-sampling
  version: "0.2.1"

source:
  url: "https://files.pythonhosted.org/packages/da/ef/a188c5b1a1df0db34fe4eabeee9b1090dc841afb8a2cf511569dd23edbdf/cluster-over-sampling-0.2.1.tar.gz"
  sha256: "015de880ed06cd677107f42131c91e78b4d88c42ea9c9f62159da482ca2265b9"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
