package:
  name: cluster-over-sampling
  version: "0.2.2"

source:
  url: "https://files.pythonhosted.org/packages/04/93/5b24b761b3722c9ec1e061c2cf9898111300440c8b44067b44c2d2fad6b0/cluster-over-sampling-0.2.2.tar.gz"
  sha256: "508ef305e46966ab4f8b9fe94d00c943ce9bf93b0cfff4dd7bc89877e15e1671"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
