package:
  name: cluster-over-sampling
  version: "0.2.5"

source:
  url: "https://files.pythonhosted.org/packages/a4/04/17cb63045347766dc30c684171b876f2596ee83188b822b6292cd9ca94af/cluster-over-sampling-0.2.5.tar.gz"
  sha256: "3d856aeb7c3e0eeff8269ccccb110d9e80667d781ad38211c789b76884e1300c"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
