package:
  name: cluster-over-sampling
  version: "0.2.6"

source:
  url: "https://files.pythonhosted.org/packages/f0/09/e652d85df08b32b261f6460729040b550db67c721b054b6e0d3e76e95827/cluster-over-sampling-0.2.6.tar.gz"
  sha256: "446975e4ad707a42f88e98212f9c2653027b6513390240cbe660d8e36323f850"

build:
  number: 0
  noarch: python

requirements:
  host:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

  run:
    - imbalanced-learn >=0.6.2
    - numpy >=1.1
    - python
    - scikit-learn >=0.22
    - scipy >=0.17

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - clover

about:
  home: "https://github.com/AlgoWit/cluster-over-sampling"
  license: "MIT"
  license_file: ""
